Homework6
AlexSP0/Notes pull request #1
Opened 2021-05-20 10:55 UTC by AlexSP0

with DataPicker

2021-05-25 13:26 UTC, NIR-Ginko requested changes
I suggest to move picture files out of `app/src/main/java/com/example/notes` directory into something like `dist` or `doc`. You can use `git mv` command to do it.

2021-05-25 13:26 UTC, NIR-Ginko commented on app/src/main/java/com/example/notes/Note.java
> +public class Note implements Serializable {
Will you implement the serialization itself?

2021-05-25 13:43 UTC, NIR-Ginko commented
Nothing to comment at the moment. I suppose I need to try to build and test the code at least once.

2021-05-28 19:11 UTC, enotniy reviewed
Ok for me

2021-05-28 19:11 UTC, enotniy commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".CurrentNoteActivity"></activity>
<activity android:name=".CurrentNoteActivity" />

2021-05-28 19:11 UTC, enotniy commented on app/src/main/java/com/example/notes/Note.java
> +        date=cal.getTimeInMillis();
форматирование

2021-05-28 19:11 UTC, enotniy commented on app/src/main/java/com/example/notes/Note.java
> +    public Calendar getDate() {
почему у тебя 2 даты в разных форматах? Одна Calendar другая long. Храни обе в Long

2021-05-28 19:11 UTC, enotniy commented on app/src/main/java/com/example/notes/NotesArray.java
> +    private ArrayList<Note> notesArray;
`private List<Note> notesArray;`

2021-05-28 19:11 UTC, enotniy commented on app/src/main/java/com/example/notes/NotesFragment.java
> +    private void ShowLandCurrentNote(Note note) {
showLandCurrentNote

2021-05-28 19:11 UTC, enotniy commented on app/src/main/java/com/example/notes/NotesFragment.java
> +    private void ShowPortCurrentNote(Note note) {
showPortCurrentNote

2021-05-30 14:36 UTC, merged